### ISSUE TITLE
Hardcoded to root of backend routes

### ISSUE THREAD

**Issue by alexfmpe** [obsidiansystems/obelisk-oauth#11]
Even though `TokenRequest` and `AuthorizationRequest` work for any `r (R OAuth)`, it looks like using them effectively forces `r` to be the app's root of backend routes.
Is this intended?

https://github.com/obsidiansystems/obelisk-oauth/blob/v0.1.0.0/backend/Obelisk/OAuth/AccessToken.hs#L30-L31

https://github.com/obsidiansystems/obelisk-oauth/blob/v0.1.0.0/common/Obelisk/OAuth/Authorization.hs#L82-L83

**Comment by 3noch** [comment]
No you should be able to choose any route.
